### ISSUE TITLE
No module named 'typing_extensions'

### ISSUE THREAD

**Issue by HXB-1997** [FGiuliari/Trajectory-Transformer#28]
`(TNTF) han@han:~/Desktop/hxb_projects/Trajectory-Transformer$ tensorboard --logdir logs
2024-12-10 09:52:36.529557: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-10 09:52:36.555218: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
TensorFlow installation not found - running with reduced feature set.
Traceback (most recent call last):
  File "/home/han/.local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/home/han/.local/lib/python3.8/site-packages/tensorboard/main.py", line 42, in run_main
    plugins=default.get_plugins(),
  File "/home/han/.local/lib/python3.8/site-packages/tensorboard/default.py", line 86, in get_plugins
    return get_static_plugins() + get_dynamic_plugins()
  File "/home/han/.local/lib/python3.8/site-packages/tensorboard/default.py", line 121, in get_dynamic_plugins
    return [
  File "/home/han/.local/lib/python3.8/site-packages/tensorboard/default.py", line 122, in <listcomp>
    entry_point.resolve()
  File "/usr/local/lib/python3.8/dist-packages/pkg_resources/__init__.py", line 2524, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/han/.local/lib/python3.8/site-packages/open3d/__init__.py", line 112, in <module>
    import open3d.visualization
  File "/home/han/.local/lib/python3.8/site-packages/open3d/visualization/__init__.py", line 19, in <module>
    from .draw_plotly import draw_plotly
  File "/home/han/.local/lib/python3.8/site-packages/open3d/visualization/draw_plotly.py", line 12, in <module>
    from dash import html
  File "/home/han/.local/lib/python3.8/site-packages/dash/__init__.py", line 5, in <module>
    from .dependencies import (  # noqa: F401,E402
  File "/home/han/.local/lib/python3.8/site-packages/dash/dependencies.py", line 2, in <module>
    from dash.development.base_component import Component
  File "/home/han/.local/lib/python3.8/site-packages/dash/development/__init__.py", line 1, in <module>
    from . import base_component  # noqa:F401
  File "/home/han/.local/lib/python3.8/site-packages/dash/development/base_component.py", line 8, in <module>
    from .._utils import patch_collections_abc, stringify_id, OrderedSet
  File "/home/han/.local/lib/python3.8/site-packages/dash/_utils.py", line 17, in <module>
    from dash.types import RendererHooks
  File "/home/han/.local/lib/python3.8/site-packages/dash/types.py", line 1, in <module>
    from typing_extensions import TypedDict, NotRequired
ModuleNotFoundError: No module named 'typing_extensions'`

**Comment by HXB-1997** [comment]
solved
这个错误提示表明系统找不到 `tensorboard` 命令，通常是因为它的执行路径没有正确添加到 `PATH` 环境变量中。

你可以通过以下几个步骤解决这个问题：

### 1. 确认 `tensorboard` 的安装位置

根据你提供的信息，TensorBoard 已经安装在 `anaconda3/envs/TNTF/lib/python3.8/site-packages` 路径下，但命令没有在 `PATH` 中。你可以通过以下命令来确认 `tensorboard` 的安装位置：

```bash
which tensorboard
```

如果系统找不到 `tensorboard` 命令，或者返回路径不正确，那么可能是该命令的可执行文件没有添加到 `PATH`。

### 2. 手动添加 `tensorboard` 到 `PATH`

在 Anaconda 环境中，通常你需要手动添加安装目录下的 `bin` 文件夹到系统的 `PATH`。可以执行以下步骤：

#### a) 确认 `tensorboard` 执行文件的位置

根据你使用的虚拟环境位置，TensorBoard 执行文件可能位于类似下面的路径：

```
/home/han/anaconda3/envs/TNTF/bin/tensorboard
```

你可以使用以下命令确认 `tensorboard` 执行文件的实际位置：

```bash
find /home/han/anaconda3/envs/TNTF/ -name tensorboard
```

#### b) 将路径添加到 `PATH` 环境变量

假设上一步查找到的路径为 `/home/han/anaconda3/envs/TNTF/bin/`，你可以通过以下方式将该路径添加到 `PATH` 环境变量中。

打开你的 `~/.bashrc` 文件（如果你使用的是 bash）：

```bash
nano ~/.bashrc
```

或者，如果你使用的是 `zsh`，则编辑 `~/.zshrc` 文件：

```bash
nano ~/.zshrc
```

在文件的末尾添加以下行：

```bash
export PATH="/home/han/anaconda3/envs/TNTF/bin:$PATH"
```

保存并退出后，执行以下命令使更改生效：

```bash
source ~/.bashrc   # 如果是 bash 用户
# 或者
source ~/.zshrc    # 如果是 zsh 用户
```

#### c) 验证

现在重新运行 `tensorboard` 命令：

```bash
tensorboard --logdir logs
```

### 3. 使用完整路径启动

如果不想修改 `PATH`，你也可以直接使用 `tensorboard` 的完整路径来启动，例如：

```bash
/home/han/anaconda3/envs/TNTF/bin/tensorboard --logdir logs
```

### 4. 重新安装（如果问题仍然存在）

如果上述步骤没有解决问题，可能是 TensorBoard 的安装不完整。你可以尝试重新安装：

```bash
pip uninstall tensorboard
pip install tensorboard
```

重新安装后，尝试再次运行 `tensorboard`。

---

希望这些方法能帮你解决问题！
